If the only node on a list is the dead node a, and a->n is a node that hasn't finished adding, then a->n->p == nil. But nil->p == a. So help_next will spuriously swing. Check whether np is nil. If so, it can't have died.
T:2 -- Begin lflist_deq(<>, 0x7fffffffe0b0:&LIST(n:{0x7ffff7ff0a50:0:0, 4021}, p:{0x7ffff7ff0a50:0:0, 2144})) in reinsert_kid:108
T:2 -- Begin lflist_del({0x7ffff7ff0a50:0:0, 2170}, <>) in lflist_deq:267
T:2 CAS! lflist_del:125 - {0x7ffff7fe1a50:0:1, 4932} if {0x7ffff7fe1a50:0:0, 4931}, addr:0x7ffff7ff0a50
T:2 WON - found:{0x7ffff7fe1a50:0:0, 4931} addr:0x7ffff7ff0a50
T:2 CAS! lflist_del:129 - {0x7ffff7fe1a50:0:0, 4022} if {0x7ffff7ff0a50:0:0, 4021}, addr:0x7fffffffe0b0
T:2 WON - found:{0x7ffff7ff0a50:0:0, 4021} addr:0x7fffffffe0b0
T:2 CAS! lflist_del:138 - {0x7fffffffe0b0:1:0, 2120} if {0x7ffff7ff0a50:0:0, 2120}, addr:0x7ffff7fe1a60
T:2 WON - found:{0x7ffff7ff0a50:0:0, 2120} addr:0x7ffff7fe1a60
T:3 WON - found:{0x7fffffffe0b0:1:0, 4930} addr:0x7ffff7ff0a50
T:3 CAS! lflist_enq:254 - {0x7ffff7fe1a50:0:0, 2145} if {0x7ffff7ff0a50:0:0, 2144}, addr:0x7fffffffe0c0
T:4 -- Begin lflist_del({0x7ffff7ff0a50:0:0, 2170}, <>) in lflist_deq:267
T:2 CAS! lflist_del:139 - {(nil):0:0, 2170} if {0x7fffffffe0b0:1:0, 2170}, addr:0x7ffff7ff0a60
T:2 WON - found:{0x7fffffffe0b0:1:0, 2170} addr:0x7ffff7ff0a60
T:2 -- End lflist_del ret: 0
T:5 -- Begin lflist_deq(<>, 0x7fffffffe0b0:&LIST(n:{0x7ffff7ff0a50:0:0, 4021}, p:{0x7ffff7ff0a50:0:0, 2144})) in reinsert_kid:108
T:4 Rarity. src/lflist.c:help_next:179. Swinging n:{0x7ffff7fe1a50:0:1, 4932} np:{0x7fffffffe0b0:1:0, 2120} npp:{0x7ffff7ff0a50:0:0, 2144}
T:4 CAS! help_next:180 - {0x7ffff7ff0a50:0:0, 2120} if {0x7fffffffe0b0:1:0, 2120}, addr:0x7ffff7fe1a60
T:4 WON - found:{0x7fffffffe0b0:1:0, 2120} addr:0x7ffff7fe1a60
T:4 Rarity. src/lflist.c:lflist_del:119. P abort
T:5 Logic error. src/lflist.c:help_next:177. Failed assertion !a.nil.
T:4 Rarity. src/lflist.c:lflist_del:143. p:{(nil):0:0, 2170}, n:{0x7ffff7fe1a50:0:1, 4932}, l:{(nil):0:0, 0}

Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7ffff52ed700 (LWP 29405)]
0x00000000004044ad in help_next (a=..., n=0x7ffff5249f00, np=0x7ffff5249ef0, t=0x40c858 <node_t>) at src/lflist.c:177
177             else return assert(!a.nil), -1;
(gdb) up
261         if(help_next((flx){.nil = 1, .pt = mpt(&l->nil)}, &n, &np, t))
(gdb) p l
$4 = (lflist *) 0x7fffffffe0b0
(gdb) p *l
$5 = {nil = {n = {{mp = 0x7ffff7fe1a50, {nil = 0, locked = 0, pt = 35184338503316}}, gen = 4022}, p = {{mp = 0x7ffff7fe1a50, {nil = 0, locked = 0,
          pt = 35184338503316}}, gen = 2145}}}
(gdb) p *l->n.mp
There is no member named n.
(gdb) p *l->nil.n.mp
$6 = {n = {{mp = 0x7fffffffe0b1, {nil = 1, locked = 0, pt = 35184372086828}}, gen = 4853}, p = {{mp = 0x7ffff7ff0a50, {nil = 0, locked = 0,
        pt = 35184338518676}}, gen = 2120}}